# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 20:49
from __future__ import unicode_literals

from django.db import migrations

from movieratings.models import Rater

def load_data(*args):
        with open("/Users/joe/Downloads/ml-100k/u.user") as raters:
            for rater in raters.readlines():
                line = rater.split("|")
                Rater.objects.create(pk=line[0], age=line[1], gender=line[2], occupation=line[3], zip_code=line[4])


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(load_data)
    ]
