# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:09
from __future__ import unicode_literals

from django.db import migrations


from movieratings.models import Rater, Movie, Review

def load_review_data(*args):
	with open("/Users/joe/Downloads/ml-100k/u.data") as reviews:
		for review in reviews.readlines():
			tab = review.split('\t')
			Review.objects.create(reviewer=Rater(tab[0]), movie=Movie(tab[1]), rating=tab[2], timestamp=tab[3])


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0003_auto_20160225_2056'),
    ]

    operations = [
    	migrations.RunPython(load_review_data)
    ]
