# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 04:32
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Avg


def rating_average(apps, schema_editor):
    Movie = apps.get_model('movieratings', 'Movie')
    Review = apps.get_model('movieratings', 'Review')

    for movie in Movie.objects.all():
        ratin_average = Review.objects.filter(movie=movie.pk).aggregate(Avg('rating'))
        movie.ratin_average = ratin_average['rating__avg']
        movie.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0004_auto_20160225_2109'),
    ]

    operations = [
    	migrations.RunPython(rating_average)
    ]
