# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0013_auto_20160227_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating_average',
            field=models.FloatField(),
        ),
    ]
